import pandas as pd
df = pd.read_csv("Dummy_Sales_Data_v1.csv")
print(df.head())
print(df.head(7))
print(df.tail())
print(df.tail(3))
print(df.sample())
print(df.info())
print(df.describe())
print(df.query("Quantity > 95"))
print(df.loc[100,'Sales_Manager'])
print(df.iloc[[100, 200],[6,3]])
print(df["Sales_Manager"].unique())
print(df["Sales_Manager"].nunique())
print(df.nunique())
print(df.isnull())
df2 = df[df["Product_Category"].isnull()]
print(df2)
print(df2.fillna("MissingInfo"))
print(df.sort_values("Quantity"))
print(df.value_counts("Sales_Manager"))
print(df.nlargest(10, "Delivery_Time(Days)"))
print(df.nsmallest(7, "Shipping_Cost(USD)"))
df1 = df.iloc[0:10, :].copy()
print(df1)
df1.rename(columns = {"Shipping_Cost(USD)": "Shipping_Cost",
                      "Delivery_Time(Days)":"DeliveryTime_in_Days"},
           inplace=True)
print(df1)
condition = df1["Status"] == "Not Shipped"
print(df1.where(condition))
print(df1.drop("OrderCode", axis=1))
#print(df1.corr())
print(df1[["Quantity","Shipping_Cost"]].corr())